#!/bin/bash

action=$1
case $action in
    "createdirs")
            $SUDO_COMMAND mkdir $PAYMENT_BASE_DIR -p
            $SUDO_COMMAND mkdir $PAYMENT_LIBS_DIR -p
            $SUDO_COMMAND mkdir $PAYMENT_LIBS_DIR/payment
            $SUDO_COMMAND mkdir $PAYMENT_LIBS_DIR/thirdparty
            $SUDO_COMMAND mkdir $PAYMENT_WARS_DIR -p
            $SUDO_COMMAND mkdir $PAYMENT_LOGS_DIR -p
            echo "DONE"
    ;;

    "deletedirs")
            $SUDO_COMMAND rm $PAYMENT_BASE_DIR -Rf
            $SUDO_COMMAND rm $PAYMENT_LOGS_DIR -Rf
            echo "DONE"
    ;;

    "copylibs")
            payment server linux updatelibs
    ;;

    "updatepaymentlib")
            $SUDO_COMMAND rm $PAYMENT_LIBS_DIR/payment/*.jar -f
            $SUDO_COMMAND cp $PAYMENT_SRC_INSTALLER_DIR/lib/payment/*.jar $PAYMENT_LIBS_DIR/payment
    ;;
    
    "updatelibs")
            $SUDO_COMMAND rm $PAYMENT_LIBS_DIR/payment/*.jar -f
            $SUDO_COMMAND rm $PAYMENT_LIBS_DIR/thirdparty/*.jar -f
            $SUDO_COMMAND cp $PAYMENT_SRC_INSTALLER_DIR/lib/payment/*.jar $PAYMENT_LIBS_DIR/payment
            $SUDO_COMMAND cp $PAYMENT_SRC_INSTALLER_DIR/lib/thirdparty/*.jar $PAYMENT_LIBS_DIR/thirdparty
            echo "DONE"
    ;;
    
    "copywars")
            payment server linux updatewars
    ;;

    "updatewars")
            $SUDO_COMMAND rm $PAYMENT_WARS_DIR/*.war -f
            $SUDO_COMMAND cp $PAYMENT_SRC_INSTALLER_DIR/lib/payment/*.war $PAYMENT_WARS_DIR
            echo "DONE"
    ;;
    
    *)
            echo "Unknown linux-server action."
    ;;
esac
